default: &default
  host: <%= ENV.fetch("HOST") { "localhost" } %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres

development:
  <<: *default
  database: abc_development

test:
  <<: *default
  database: abc_test

production:
  <<: *default
  database: abc_production
  username: abc
  password: <%= ENV['ABC_DATABASE_PASSWORD'] %>
